### ISSUE TITLE
runsd plugin for Dapr?

### ISSUE THREAD

**Issue by Brian-McBride** [ahmetb/runsd#26]
There is an interesting project, [Dapr](https://docs.dapr.io/), that provides some common interfaces for typical microservices work. It's not crazy unique, but it has potential. 

Like `runsd`, `dapr` uses a sidecar architecture. They have "Pluggable service discovery" but I don't see something that works super well with Cloud Run fully managed right out of the box. I suppose I could make it work with [GCP Service Directory](https://cloud.google.com/service-directory).

But then, I thought it should be pretty for you to drop runsd as a plugin. I mean, the basic DNS package they have looks like:
```golang
func (k *resolver) ResolveID(req nameresolution.ResolveRequest) (string, error) {
	return fmt.Sprintf("%s-dapr.%s.svc:%d", req.ID, req.Namespace, req.Port), nil
}
```

I'm throwing this out there because I do not currently have time to dive into Go and figure out how to add this as a plugin there. And while I'm not a huge fan of ORMs, I can appreciate a lot of the abstraction Dapr is offering.

**Comment by ahmetb** [comment]
Good idea but probably not in the scope for this repository. This repo is a standalone tool that does the job by reimplementing a lot of stuff from scratch.

You should feel free to run with that idea and contribute it to Dapr. I assume Dapr also can add authentication tokens to outgoing requests. If that is pluggable as well, you can also automatically get a token from the metadata service and augment the Cloud Run-to-Cloud Run request with that as well.

I'm closing since it's not something we'd do in this repo plus I do not know much Dapr myself. Thanks for bringing it up. 👍🏼
